### ISSUE TITLE
Install via Console

### ISSUE THREAD

**Issue by Rondoozle** [EvolSoft/AutoUpdater#1]
How can I install AutoUpdater via console? I do not have a GUI.

**Comment by Flavius12** [comment]
Can you be more detailed?
Where are you running PocketMine? On a VPS?
What Operating System are you using?

**Comment by Rondoozle** [comment]
I am running PocketMine-MP 1.5dev -1240 on a VPS that is running Ubuntu 14.04 x64.

**Comment by Flavius12** [comment]
Try with wget. However this issue is not related to the plugin

**Comment by Sidmit867** [comment]
How do I update my server using this
